resources:
- name: every-1m
  type: time
  source: {interval: 1m}

- name: github-code
  type: git
  source:
    uri: https://github.com/vlad-stoian/rabbot.git
    branch: master

jobs:
- name: navi
  plan:
  - get: every-1m
    trigger: true
  - get: github-code
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: alpine
      run:
        path: python
        args:
        - "github-code/src/check-it.py"

